name: testnico
favicon: null
layout_spectrum: 0
typography_spectrum: 0.002339139813557267
title: Test SoyHuCe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7155334027484059
  lightness: 0.887559687718749
  saturation: 0.5465292218141258
  rhythmicContrast: 0.75
purpose: []
